# config/packages/security.yaml

security:
    # Hashage des mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Chargement des utilisateurs depuis la base de données
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login         # Route du formulaire de login
                check_path: app_login         # Route de vérification du login
                default_target_path: /meubles # Redirection après login
            logout:
                path: app_logout
                target: /login                # Redirection après logout

    # Contrôle d'accès
    access_control:
        
        - { path: ^/meubles, roles: ROLE_USER }
        - { path: ^/category, roles: ROLE_USER }
